### ISSUE TITLE
Persistent sort order

### ISSUE THREAD

**Issue by adelespinasse** [benjaffe/chrome-okc-plugin#110]
This is a feature request.

When searching for matches ("Browse Matches"), OkC always defaults to sorting by "Special Blend". I wish it would default to whatever order I used most recently. Or just default to sorting by match %, which is what I usually want, but that's just me.

Similarly, when browsing someone's profile, if I click on "The two of us", I wish it would default to the "what I care about" category. In fact, I'm really confused about why OkC doesn't do this, since the questions I care about are the ones I care about... but in case other people prefer to see a different category, I think the best default would be whatever they chose most recently.

**Comment by benjaffe** [comment]
Due to OkC's regular site updates, I'm paring down the feature list to focus on core functionality. Marking this as a wont-implement.
