### ISSUE TITLE
Dynamic "What I care about" category

### ISSUE THREAD

**Issue by studgeek** [benjaffe/chrome-okc-plugin#113]
From my work adding #89 I came up with what I think is an interesting idea. Since you are scanning "What I care about" for each profile to get their answers for scoring, why not also create a dynamic, personalized "What I care about" category also while doing the scanning?

So right on each user profile you can see at a glance their score for "Very Important" questions and the answers on the right (like any category).

**Comment by astronouth7303** [comment]
You mean like how OkCupid calculates their percent?

**Comment by studgeek** [comment]
I'm talking about a window on a slice of that, just like the existing categories. OkCupid's % is based on all questions for us and them (sorry for using us/them - it just makes description simpler).

I'm suggesting a category for just for the questions we care about a lot. You're right that since we care a lot about them they are heavily weighted in the percentage. So the N/M score is probably less valuable.  (since the OkCupid already heavily weights those answers), but the real value is we can see our top question's answers right on the profile page.

And the extension already walks our "what we care about" questions list for each profile we view. So there is no additional scanning overhead.

**Comment by benjaffe** [comment]
That sounds like a wonderful idea if you can build UI for it. That seems
like the most challenging part. I'd love to see that in the plugin!
