### ISSUE TITLE
New design, plugin covers "My Details"

### ISSUE THREAD

**Issue by instantgreen** [benjaffe/chrome-okc-plugin#120]
Yeah, as the title says, the plugin needs to move a bit farther right.

Thanks!

EDIT: Oh, and the overview with all the categories at the top needs to move a bit farther left.

EIDT2: Hovering over profile pictures and seeing an enlarged version of the photo doesn't work anymore, neither.

**Comment by Stragis** [comment]
Bump

**Comment by benjaffe** [comment]
Nice -- I'm on vacation without my computer, so I'll try and get to that in a few days when I return.

**Comment by benjaffe** [comment]
Thanks Evan for your work on this. The fix should land within the hour.
