### ISSUE TITLE
[CSS] Profile Picture clips the question hover

### ISSUE THREAD

**Issue by astronouth7303** [benjaffe/chrome-okc-plugin#123]
![screenshot](https://cloud.githubusercontent.com/assets/401438/7555971/d6c383a6-f72b-11e4-907a-be46f22138af.png)

**Comment by benjaffe** [comment]
Is this still an issue? When I click Photos, I get a gallery list, and when I click on a gallery, it shows the photos full-screen. @astronouth7303 re-open this issue if it's still relevant, but I can't repro it for now, so I'm closing the issue. :)

**Comment by astronouth7303** [comment]
Still an issue. It's when you hover over one of the categories. May only occur on narrow displays.
