### ISSUE TITLE
Process of increasing plugin accuracy asks questions that have been answered already

### ISSUE THREAD

**Issue by instantgreen** [benjaffe/chrome-okc-plugin#130]
As the title says, the plugin asks these questions again, which is especially annoying if one selected opposing categories with the same questions. 

Is this intentional behaviour (because maybe people would like to think about their already answered questions once more and increase their importance?)? Could something be done about this?

**Comment by benjaffe** [comment]
Definitely not intentional. Maybe OkC's design changes resulted in the plugin not recognizing when questions have been answered already. IIRC, it looks for a DOM node, and if it finds it (or if it's visible), it assumes the question has been answered. The UI changes might have broken that behavior.

**Comment by benjaffe** [comment]
Due to OkC's regular site updates, I'm removing the "improve accuracy" feature.
