### ISSUE TITLE
Could you add questions relevant to solo polyamory?

### ISSUE THREAD

**Issue by AggieSez** [benjaffe/chrome-okc-plugin#134]
Solo poly folks aren't coupled up or interested in entwining their lives deeply (sharing a home, finances, etc.) with any romantic partners. Those of us who are solo poly find it helpful to determine how compatible potential partners/dates might be with our preferences.

My friend Hannah Darvill recently added some OKC questions helpful for determining compatibility with solo polyamory. Think you could add these to your filters for the plugin?

1. https://www.okcupid.com/questions?rqid=464140
2. https://www.okcupid.com/questions?rqid=464141
3. https://www.okcupid.com/questions?rqid=461934
4. https://www.okcupid.com/questions?rqid=464142

Thanks!

**Comment by lindes** [comment]
+1... I'm not certain I even identify as "Solo Poly", and yet I find these questions to be rather useful... And various answers are certainly relevant to polyamory in general, and/or all would be relevant to a potential new plugin category for solo poly specifically.

**Comment by benjaffe** [comment]
Absolutely. On vacation with no computer, but I'll look at this in a month.
If someone makes a pull request, it'll get done as soon as I'm home.
