### ISSUE TITLE
Question formatting update broke plugin completely

### ISSUE THREAD

**Issue by Xanterra** [benjaffe/chrome-okc-plugin#183]
Hey, I absolutely love your plugin, but unfortunately the recent update to how questions are displayed broke it. If you get a chance to update it, I'm sure it'll make a lot of people happy.

**Comment by benjaffe** [comment]
Oh poop. It might be a while before I can look at this. What a bummer.
Thanks for the report!

**Comment by mallooh** [comment]
Yes please! This app has helped me and so many in the community!

**Comment by benjaffe** [comment]
I might get around to rewriting the plugin, but no promises. If you want to be notified if the plugin starts working again, fill this out.

https://docs.google.com/forms/d/1zyFoKPSxwYFnWHmJ--zeN6nwvaH-bzfmMyeUJ_cgpt4

**Comment by damiendr** [comment]
FWIW, I found that one can access the answers this way:

```javascript
const rq = new XMLHttpRequest();
rq.open("GET", "https://www.okcupid.com/1/apitun/profile/PROFILE_ID/answers?after=XXXX&_=TIMESTAMP")
rq.setRequestHeader("authorization", "Bearer ".concat(ACCESS_TOKEN))
rq.send()
```
where TIMESTAMP is the current timestamp (?) with millis eg. 1548000978996
and XXXX is either empty for the first question or `window.btoa("10,")` to start at the 10th question.

**Comment by benjaffe** [comment]
@damiendr Awesome! Thank you for that... handy that they store the access token in a global variable.

**Comment by Xanterra** [comment]
Thanks so much for the update!

**Comment by benjaffe** [comment]
Thank You @damiendr !
